name: 'Setup ccache (Windows, Linux, MacOs)'
description: 'A github action to speedup cmake builds using ccache'
author: 'Chirag Singla <chirag.singla.pi@gmail.com>'
inputs:
  key:
    description: "A key to access and update cache"
    required: true
    default: "ccache-key"
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/cache/index.js'
