name: 'Setup ccache (Windows, Linux, MacOs)'
description: 'A github action to speedup cmake builds using ccache'
author: 'Chirag Singla <chirag.singla.pi@gmail.com>'
icon: archive
inputs:
  key:
    description: "A key to access and update cache"
    required: false
    default: "ccache-key"
  cache_dir:
    description: "Specifies where ccache will keep its cached compiler outputs."
    requires: false
    default: ".ccache"
  compiler:
    description: "Force the name of the compiler to use."
    required: false
    default: ""
  path:
    description: "If set, ccache will search directories in this list when looking for compiler"
    required: false
    
runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/cache/index.js'
