name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install

      - name: "Lint and build"
        run: npm run all

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Setup ccache"
        uses: ./
        with:
          key: "ccache-key"
