name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Install dependencies"
        run: npm install

      - name: "Lint and build"
        run: npm run all

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            path: "C:/msys64/mingw64/bin/"

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup ccache"
        uses: ./
        with:
          key: "ccache-key"
          cache_dir: ".ccache"
          path: ${{ matrix.path }}

      - name: "Run with cmake"
        uses: lukka/run-cmake@v3.4
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/examples/CMakeLists.txt'
          cmakeAppendedArgs: '-D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
          buildWithCmake: true
          buildDirectory: '${{ github.workspace }}/examples/build'
